version: "2.30.1"

services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: data_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  setup_db:
    build: .
    command: /bin/sh -c "python setup_db.py && python ETL/load_processed_data.py"
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - my_network

  app:
    build: .
    command: /bin/sh -c "python app.py"
    depends_on:
      - setup_db
    ports:
      - "5000:5000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge